### ISSUE TITLE
CLI: a command that needs a DB should fail cleanly when the backend is None

### ISSUE THREAD

**Issue by anilmurty** [Metabuilder-Labs/openclawwatch#727]
Surfaced while reviewing #726.

When a command runs with `ctx.obj["db"] = None`, it currently dereferences the `None` and raises a raw traceback rather than telling the user what went wrong.

Reproduction (needs #726 or the `no_db_commands` path):

```
tj loop annotate SID --note --help
→ AttributeError: 'NoneType' object has no attribute 'execute'   (core/loop.py:160)
```

This is pre-existing and not caused by #726 — `no_db_commands` has the same shape. Any command that skips `open_db()` and then reaches DB-touching code produces a traceback instead of a message.

`cmd_optimize` already handles this by hand:

> `optimize requires either a direct DuckDB connection or a running tj serve at the configured api.{host,port}.`

That is the right behaviour; it just isn't shared. `loop annotate` and any other DB-touching command outside `no_db_commands` have nothing equivalent.

## Done when

- A single shared guard (a decorator, or a check in `TjCommand.invoke`) raises a `ClickException` naming the command when a DB-requiring command finds `db is None`
- `cmd_optimize`'s hand-rolled version is replaced by it, so there is one copy of the message rather than two
- A test asserts the clean error rather than the traceback, for at least one command that is not `optimize`

Nothing is written on the current crash path, so this is a diagnostics problem rather than a data-integrity one.
